---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

ENABLE_LINTERS:
  - ANSIBLE_ANSIBLE_LINT
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - GO_GOLANGCI_LINT
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_PYLINT
  - YAML_YAMLLINT
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SYFT
  - RUBY_RUBOCOP
DISABLE:
  - COPYPASTE
  - REPOSITORY
  - SPELL
DISABLE_ERRORS: false
FILTER_REGEX_EXCLUDE: (\.github|development)
FLAVOR_SUGGESTIONS: false
JSON_REPORTER: true
JSON_REPORTER_OUTPUT_DETAIL: simple
VALIDATE_ALL_CODEBASE: true
